services:
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: musaca
    volumes:
      - musaca-db:/var/lib/postgres/data
volumes:
  musaca-db:


