services:
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: musaca
    volumes:
      - musaca-db:/var/lib/postgres/data
volumes:
  musaca-db:


